<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <DebugType>none</DebugType>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="AOTrino" />
    <Using Include="AOTrino.Bridge" />
    <Using Include="AOTrino.Input" />
    <Using Include="AOTrino.Resources" />
    <Using Include="AOTrino.Utilities" />
    <Using Include="DirectN" />
    <Using Include="DirectN.Extensions" />
    <Using Include="DirectN.Extensions.Com" />
    <Using Include="DirectN.Extensions.Utilities" />
    <Using Include="WebView2" />
    <Using Include="WebView2.Utilities" />
    <Using Alias="DirectNConstants" Include="DirectN.Constants" />
    <Using Alias="DirectNFunctions" Include="DirectN.Functions" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="README.md" />
    <EmbeddedResource Include="src\Presentation\Web\assets\index.html" />
    <EmbeddedResource Include="src\Presentation\Web\assets\app.js" />
    <EmbeddedResource Include="src\Presentation\Web\assets\styles.css" />
    <EmbeddedResource Include="src\Presentation\Desktop\assets\index.html" />
    <EmbeddedResource Include="src\Presentation\Desktop\assets\app.js" />
    <EmbeddedResource Include="src\Presentation\Desktop\assets\styles.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AOTrino" Version="1.1.1" />
  </ItemGroup>

</Project>
